"""initial schema with profile fields

Revision ID: 4ba49cf12b8e
Revises: 
Create Date: 2026-06-17 17:13:11.694459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba49cf12b8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('target_role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'target_role')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
